version: 2.1

setup: true

parameters:
  base-revision:
    type: string
    default: "main"
  product:
    default: "none"
    description: Select the product to build
    type: enum
    enum: ["vb6", "GIS108", "Pro31", "build-all", "none"]
  build-all:
    type: boolean
    default: false
  build-ibase-binaries:
      description: Match any files to trigger building iBase .Net Binaries
      type: string
      default: ^((build\/(iBase|Common)|src\/iBase|src\/(Common|Graphics|Notebook|Shared|Targets))\/.*)|(src\/Solutions\/i2.iBase.All.Working.sln)


orbs:
  path-filtering: circleci/path-filtering@1.0.0
  continuation: circleci/continuation@1.0.0

jobs:
  run-continuation-config:
    docker:
      - image: cimg/python:3.8
    steps:
     - checkout
     - when:
          condition:
            and:
             - equal: ["none", << pipeline.parameters.product >>]
          steps:
            - run:
                name: No parameter entered. Doing path-filtering
                command: echo "No parameter entered. Doing path-filtering"
            - path-filtering/set-parameters:
                base-revision: << pipeline.parameters.base-revision >>
                output-path: "/tmp/pipeline-parameters.json"
                mapping: |
                  src/dependancies/.* build-all true
                  << pipeline.parameters.build-ibase-binaries >> build-ibase-binaries true
            - continuation/continue:
                configuration_path: .circleci/continue_config.yml
                parameters: /tmp/pipeline-parameters.json
     - when:
          condition:
            and:
              - not:
                  equal: ["none", << pipeline.parameters.product >>]
          steps:
            - run:
                name: Triggered with a parameter. Building << pipeline.parameters.product >>
                command: |
                  echo "Building << pipeline.parameters.product >>"
            - continuation/continue:
                configuration_path: .circleci/continue_config.yml


workflows:
  setup-workflow:
    jobs:
      - run-continuation-config