version: 2.1

setup: true

parameters:
  base-revision:
    type: string
    default: "main"
  vb6:
    type: boolean
    default: false
  GIS108:
    type: boolean
    default: false
  Pro31:
    type: boolean
    default: false
  build-all:
    type: boolean
    default: false

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          mapping: |
            build/vb6/.* vb6 true
            ^.*ArcGIS108.* GIS108 true
            ^.*ArcGISPro31.* Pro31 true
            src/dependancies/.* build-all true
          # # Optional, defaults to main:
          base-revision: << pipeline.git.base_revision >>