version: 2.1

setup: true

parameters:
  base-revision:
    type: string
    default: "main"

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          mapping: |
            build/vb6/.* vb6 true
            ^.*ArcGIS108.* GIS108 true
            ^.*ArcGISPro31.* Pro31 true
          # # Optional, defaults to main:
          base-revision: << pipeline.git.base_revision >>