version: 2.1

setup: true

parameters:
  base-revision:
    type: string
    default: "main"
  product:
    default: "none"
    description: Select the product to build
    type: enum
    enum: ["all", "vb6", "GIS108", "Pro31", "buildall", "none"]
  build-all:
    type: boolean
    default: false

orbs:
  path-filtering: circleci/path-filtering@1.0.0
  continuation: circleci/continuation@1.0.0

jobs:
  run-continuation-config:
    docker:
      - image: cimg/python:3.8
    steps:
     - checkout
     - when:
          condition:
            and:
             - equal: ["none", << pipeline.parameters.product >>]
          steps:
              # The path-filtering/filter job determines which pipeline parameters to update.
            - path-filtering/set-parameters:
                base-revision: main
                output-path: "/tmp/pipeline-parameters.json"
                mapping: |
                  src/dependancies/.* build-all true
            - continuation/continue:
                configuration_path: .circleci/continue_config.yml
                parameters: /tmp/pipeline-parameters.json
     - when:
          condition:
            and:
              - not:
                  equal: ["none", << pipeline.parameters.product >>]
          steps:
            - run:
                command: |
                  # echo '{ "product": "<< pipeline.parameters.product >>" }' > /tmp/pipeline-parameters.json
                  echo << pipeline.parameters.product >>
            - continuation/continue:
                configuration_path: .circleci/continue_config.yml
                # parameters: /tmp/pipeline-parameters.json


workflows:
  setup-workflow:
    jobs:
      - run-continuation-config