version: 2.1

parameters:
  product:
    default: "none"
    description: Select the product to build
    type: enum
    enum: ["vb6", "GIS108", "Pro31", "build-all", "none"]

jobs:
  vb6-build:
    docker:
      - image: cimg/base:2021.01
    steps:
      - run:
          name: echo Hello
          command: |
            echo "This is the vb6 build"
  GIS108-build:
    docker:
      - image: cimg/base:2021.01
    steps:
      - run:
          name: echo Hello
          command: |
            echo "This is the GIS108 build"
  pro31-build:
    docker:
      - image: cimg/base:2021.01
    steps:
      - run:
          name: echo Testing
          command: |
            echo "This is the Pro31 build"

workflows:
  vb6:
    when: 
      equal: ["vb6", << pipeline.parameters.product >>]
    jobs:
      - vb6-build
  GIS108:
    when: 
      equal: ["GIS108", << pipeline.parameters.product >>]
    jobs:
      - GIS108-build
  pro31:
    when: 
      equal: ["Pro31", << pipeline.parameters.product >>]
    jobs:
      - pro31-build
  build-all:
    when: 
      equal: ["build-all", << pipeline.parameters.product >>]
    jobs:
      - GIS108-build
      - pro31-build:
          requires:
            - GIS108-build
