version: 2.1

parameters:
  vb6:
    type: boolean
    default: false
  GIS108:
    type: boolean
    default: false
  Pro31:
    type: boolean
    default: false
  build-all:
    type: boolean
    default: false

jobs:
  vb6-build:
    docker:
      - image: cimg/base:2021.01
    steps:
      - run:
          name: echo Hello
          command: |
            echo "This is the vb6 build"
  GIS108-build:
    docker:
      - image: cimg/base:2021.01
    steps:
      - run:
          name: echo Hello
          command: |
            echo "This is the GIS108 build"
  pro31-build:
    docker:
      - image: cimg/base:2021.01
    steps:
      - run:
          name: echo Testing
          command: |
            echo "This is the Pro31 build"

workflows:
  vb6:
    when: << pipeline.parameters.vb6 >>
    jobs:
      - vb6-build
  GIS108:
    when: << pipeline.parameters.GIS108 >>
    jobs:
      - GIS108-build
  pro31:
    when: << pipeline.parameters.Pro31 >>
    jobs:
      - pro31-build
  build-all:
    when: << pipeline.parameters.build-all >>
    jobs:
      - GIS108-build
      - pro31-build:
          requires:
            - GIS108-build
